/**
 * FieldPulse Pricebook 2.0 â€” Calculated Column Registry
 *
 * Canonical source of truth for every ARRAYFORMULA on the Items,
 * Item Option Values, and Item Groupings sheets, plus per-cell tier
 * formulas on the Variables sheet.
 *
 * Consumed by repairCalculatedColumns() in Menu.gs.
 *
 * Each entry in CALC_SHEETS maps a column letter to its anchor-row-2
 * ARRAYFORMULA. Repair clears the column body (row 2 â†’ maxRow) and
 * writes the formula back at row 2; the ARRAYFORMULA spills the rest.
 *
 * Spill prevention: repairErrantCalculatedColumns() in Menu.gs
 * unconditionally sweeps row 3 â†’ maxRows on every registry column before
 * rewriting any errant anchor, so orphan static values below the anchor
 * cannot block the spill.
 *
 * Flat-fee pass-through branch (Service surcharges, etc.):
 *   Items: flat = (Type="SERVICE") * (Markup=1)
 *   Item Option Values: flat = (Markup=1)
 *   When flat, Energy Surcharge = 0, Landed Cost = 0,
 *   Price = Cost, Net Markup = 1.
 *
 * Variables tier formulas (per-cell, not ARRAYFORMULA) are generated by
 * buildVariablesTierFormulas_() from VARIABLES_TIER_TABLES. Repair for
 * these lives in Menu.gs as a separate function from
 * repairCalculatedColumns(); see VARIABLES_TIER_FORMULAS below.
 */

const CALC_SHEETS = [
  // ===========================================================================
  // ITEMS â€” 28 ARRAYFORMULAs
  // ===========================================================================
  {
    name: 'Items',
    displayLabel: 'Items',
    headerRow: 1,
    formulas: {
      J: `=ARRAYFORMULA(LET(
  cat,D2:D, cost,H2:H, typ,F2:F,
  rate,Variables!$C$4,
  gate,(cat<>"")*
       ((ISNUMBER(SEARCH("GLASS",cat))+ISNUMBER(SEARCH("IGU",cat))+ISNUMBER(SEARCH("MIRROR",cat)))>0)*
       ((ISNUMBER(SEARCH("HARDWARE",cat))+ISNUMBER(SEARCH("OTHER",cat)))=0)*
       (UPPER(TRIM(typ))<>"SERVICE"),
  IF(cost="","",cost*rate*gate)
))`,
      K: `=ARRAYFORMULA(LET(
  cat,D2:D, cost,H2:H, markup,I2:I, typ,F2:F,
  rate,Variables!$C$4, mode,Variables!$C$5,
  flat,(UPPER(TRIM(typ))="SERVICE")*(markup=1),
  gate,(cat<>"")*
       ((ISNUMBER(SEARCH("GLASS",cat))+ISNUMBER(SEARCH("IGU",cat))+ISNUMBER(SEARCH("MIRROR",cat)))>0)*
       ((ISNUMBER(SEARCH("HARDWARE",cat))+ISNUMBER(SEARCH("OTHER",cat)))=0)*
       (UPPER(TRIM(typ))<>"SERVICE"),
  surcharge,cost*rate*gate,
  IF(cost="","",IF(flat,0,cost+IF(mode="Markup",surcharge,0)))
))`,
      L: `=ARRAYFORMULA(LET(
  cat,D2:D, cost,H2:H, markup,I2:I, typ,F2:F,
  rate,Variables!$C$4, mode,Variables!$C$5,
  flat,(UPPER(TRIM(typ))="SERVICE")*(markup=1),
  gate,(cat<>"")*
       ((ISNUMBER(SEARCH("GLASS",cat))+ISNUMBER(SEARCH("IGU",cat))+ISNUMBER(SEARCH("MIRROR",cat)))>0)*
       ((ISNUMBER(SEARCH("HARDWARE",cat))+ISNUMBER(SEARCH("OTHER",cat)))=0)*
       (UPPER(TRIM(typ))<>"SERVICE"),
  surcharge,cost*rate*gate,
  landed,cost+IF(mode="Markup",surcharge,0),
  IF((cost="")+(markup="")>0,"",IF(flat,cost,landed*markup+IF(mode="Markup",0,surcharge)))
))`,
      M: `=ARRAYFORMULA(LET(
  cost,H2:H, price,L2:L, markup,I2:I, typ,F2:F,
  flat,(UPPER(TRIM(typ))="SERVICE")*(markup=1),
  IF(flat,
    IF(cost="","",1),
    IF((cost="")+(price="")+(IFERROR(cost*1,0)=0)>0,"",price/cost))
))`,
      AB: `=ARRAYFORMULA(IF((A2:A=TRUE)*(E2:E<>""),REGEXREPLACE(TRIM(E2:E),"\\s+"," "),""))`,
      AC: `=ARRAYFORMULA(IF((A2:A=TRUE)*(E2:E<>""),UPPER(IF(REGEXMATCH(LOWER(TRIM(E2:E)),"hardware$"),(IF(REGEXMATCH(SUBSTITUTE(LOWER(E2:E),"pet door","pet"),"restoration"),IF(REGEXMATCH(SUBSTITUTE(LOWER(E2:E),"pet door","pet"),"glass"),"RESTORATION-GLASS",IF(REGEXMATCH(SUBSTITUTE(LOWER(E2:E),"pet door","pet"),"window"),"RESTORATION-WINDOWS","RESTORATION")),IF(REGEXMATCH(SUBSTITUTE(LOWER(E2:E),"pet door","pet"),"igu"),"GLASS-IGU",IF(REGEXMATCH(SUBSTITUTE(LOWER(E2:E),"pet door","pet"),"screen")*REGEXMATCH(SUBSTITUTE(LOWER(E2:E),"pet door","pet"),"door"),"SCREENS-DOORS",IF(REGEXMATCH(SUBSTITUTE(LOWER(E2:E),"pet door","pet"),"storefront|commercial"),"STOREFRONT",IF(REGEXMATCH(SUBSTITUTE(LOWER(E2:E),"pet door","pet"),"shower"),"SHOWERBATH",IF(REGEXMATCH(SUBSTITUTE(LOWER(E2:E),"pet door","pet"),"skylight"),"SKYLIGHTS",IF(REGEXMATCH(SUBSTITUTE(LOWER(E2:E),"pet door","pet"),"mirror"),"MIRRORS",IF(REGEXMATCH(SUBSTITUTE(LOWER(E2:E),"pet door","pet"),"window"),"WINDOWS",IF(REGEXMATCH(SUBSTITUTE(LOWER(E2:E),"pet door","pet"),"screen"),"SCREENS",IF(REGEXMATCH(SUBSTITUTE(LOWER(E2:E),"pet door","pet"),"door"),"DOORS",IF(REGEXMATCH(SUBSTITUTE(LOWER(E2:E),"pet door","pet"),"glass"),"GLASS","MISC"))))))))))))&(IF(TRIM(REGEXREPLACE(REGEXREPLACE(LOWER(E2:E),"\\b(commercial|storefront|glass|igu|mirror|doors?|screens?|windows?|skylights?|shower|bath|hardware)\\b","")," +"," "))="","","-"&SUBSTITUTE(TRIM(REGEXREPLACE(REGEXREPLACE(LOWER(E2:E),"\\b(commercial|storefront|glass|igu|mirror|doors?|screens?|windows?|skylights?|shower|bath|hardware)\\b","")," +"," "))," ","-")))&"-HDWR",(IF(REGEXMATCH(SUBSTITUTE(LOWER(E2:E),"pet door","pet"),"restoration"),IF(REGEXMATCH(SUBSTITUTE(LOWER(E2:E),"pet door","pet"),"glass"),"RESTORATION-GLASS",IF(REGEXMATCH(SUBSTITUTE(LOWER(E2:E),"pet door","pet"),"window"),"RESTORATION-WINDOWS","RESTORATION")),IF(REGEXMATCH(SUBSTITUTE(LOWER(E2:E),"pet door","pet"),"igu"),"GLASS-IGU",IF(REGEXMATCH(SUBSTITUTE(LOWER(E2:E),"pet door","pet"),"screen")*REGEXMATCH(SUBSTITUTE(LOWER(E2:E),"pet door","pet"),"door"),"SCREENS-DOORS",IF(REGEXMATCH(SUBSTITUTE(LOWER(E2:E),"pet door","pet"),"storefront|commercial"),"STOREFRONT",IF(REGEXMATCH(SUBSTITUTE(LOWER(E2:E),"pet door","pet"),"shower"),"SHOWERBATH",IF(REGEXMATCH(SUBSTITUTE(LOWER(E2:E),"pet door","pet"),"skylight"),"SKYLIGHTS",IF(REGEXMATCH(SUBSTITUTE(LOWER(E2:E),"pet door","pet"),"mirror"),"MIRRORS",IF(REGEXMATCH(SUBSTITUTE(LOWER(E2:E),"pet door","pet"),"window"),"WINDOWS",IF(REGEXMATCH(SUBSTITUTE(LOWER(E2:E),"pet door","pet"),"screen"),"SCREENS",IF(REGEXMATCH(SUBSTITUTE(LOWER(E2:E),"pet door","pet"),"door"),"DOORS",IF(REGEXMATCH(SUBSTITUTE(LOWER(E2:E),"pet door","pet"),"glass"),"GLASS","MISC"))))))))))))&IF((B2:B<>"")*(C2:C<>""),"-"&SUBSTITUTE(B2:B,CHAR(34),"")&"-"&SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(C2:C,"Patterned / Textured, Annealed","PT-A"),"Patterned / Textured, Tempered","PT-T"),"Reflective / Tinted, Annealed","RT-A"),"Reflective / Tinted, Tempered","RT-T"),"Laminated, Annealed","IMPACT"),"Annealed","A"),"Tempered","T"),"Laminated","L"),"Mirror","M"),", Specialty","-SP"),IF(TRIM(REGEXREPLACE(E2:E,"^(Commercial Storefront|IGU|Monolithic Glass|Flat Mirror|Glass Hardware|Mirror Hardware|Glass|Mirror|Shower|Doors?|Screens?|Skylights?|Windows?)( Restoration)?\\s*",""))="","","-"&REGEXREPLACE(REGEXREPLACE(REGEXREPLACE(UPPER(REGEXREPLACE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(TRIM(REGEXREPLACE(E2:E,"^(Commercial Storefront|IGU|Monolithic Glass|Flat Mirror|Glass Hardware|Mirror Hardware|Glass|Mirror|Shower|Doors?|Screens?|Skylights?|Windows?)( Restoration)?\\s*",""))," / ","-"),"(",""),")",""),CHAR(34),"")," ","-"),"-+","-")),"-SINGLE$","-S"),"-DOUBLE$","-D"),"-TRIPLE$","-T"))))&IF(AD2:AD="product","-P",IF(AD2:AD="service","-S",""))),""))`,
      AD: `=ARRAYFORMULA(IF((A2:A=TRUE)*(E2:E<>""),LOWER(TRIM(F2:F)),""))`,
      O: `=ARRAYFORMULA(IF((A2:A=TRUE)*(E2:E<>""),1,""))`,
      P: `=ARRAYFORMULA(IF((A2:A=TRUE)*(E2:E<>""),IF(TRIM(F2:F)="Product","Yes",IF(TRIM(F2:F)="Service","No","")),""))`,
      AE: `=ARRAYFORMULA(IF((A2:A=TRUE)*(E2:E<>""),0,""))`,
      AF: `=ARRAYFORMULA(IF((A2:A=TRUE)*(E2:E<>""),0,""))`,
      AG: `=ARRAYFORMULA(IF((A2:A=TRUE)*(N2:N<>""),SUBSTITUTE(N2:N,", ",","),""))`,
      AH: `=ARRAYFORMULA(IF((A2:A=TRUE)*(G2:G<>""),TRIM(G2:G),""))`,
      AI: `=ARRAYFORMULA(IF((A2:A=TRUE)*(E2:E<>""),IF(K2:K="",0,K2:K),""))`,
      AJ: `=ARRAYFORMULA(IF((A2:A=TRUE)*(E2:E<>""),IF(L2:L="",0,L2:L),""))`,
      AK: `=ARRAYFORMULA(IF((A2:A=TRUE)*(E2:E<>""),IF(ISNUMBER(SEARCH("IGU",D2:D)),VLOOKUP("Min. IGU Size Charged",Variables!A:C,3,FALSE),IF((D2:D="GLASS")+(D2:D="MIRRORS")>0,VLOOKUP("Min. Glass Size Charged",Variables!A:C,3,FALSE),"")),""))`,
      AL: `=ARRAYFORMULA(IF((A2:A=TRUE)*(E2:E<>""),IF(ISNUMBER(SEARCH("IGU",D2:D)),IFERROR(VLOOKUP("Max IGU Size "&B2:B&" "&IF(ISNUMBER(SEARCH("Tempered",C2:C)),"T","A"),Variables!A:C,3,FALSE),""),IF((D2:D="GLASS")+(D2:D="MIRRORS")>0,IFERROR(VLOOKUP("Max GLASS Size "&B2:B&" "&IF(ISNUMBER(SEARCH("Tempered",C2:C)),"T","A"),Variables!A:C,3,FALSE),""),"")),""))`,
      AO: `=ARRAYFORMULA(IF((A2:A=TRUE)*(O2:O<>""),TRIM(O2:O),""))`,
      AP: `=ARRAYFORMULA(IF((A2:A=TRUE)*(P2:P<>""),TRIM(P2:P),""))`,
      AQ: `=ARRAYFORMULA(IF((A2:A=TRUE)*(Q2:Q<>""),TRIM(Q2:Q),""))`,
      AR: `=ARRAYFORMULA(IF((A2:A=TRUE)*(R2:R<>""),TRIM(R2:R),""))`,
      AS: `=ARRAYFORMULA(IF((A2:A=TRUE)*(S2:S<>""),TRIM(S2:S),""))`,
      AT: `=ARRAYFORMULA(IF((A2:A=TRUE)*(T2:T<>""),TRIM(T2:T),""))`,
      AU: `=ARRAYFORMULA(IF((A2:A=TRUE)*(U2:U<>""),TRIM(U2:U),""))`,
      AV: `=ARRAYFORMULA(IF((A2:A=TRUE)*(V2:V<>""),TRIM(V2:V),""))`,
      AW: `=ARRAYFORMULA(IF((A2:A=TRUE)*(W2:W<>""),TRIM(W2:W),""))`,
      AX: `=ARRAYFORMULA(IF((A2:A=TRUE)*(X2:X<>""),TRIM(X2:X),""))`,
      AY: `=ARRAYFORMULA(IF((A2:A=TRUE)*(Y2:Y<>""),TRIM(Y2:Y),""))`
    }
  },

  // ===========================================================================
  // ITEM OPTION VALUES â€” 9 ARRAYFORMULAs
  // ===========================================================================
  {
    name: 'Item Option Values',
    displayLabel: 'Item Option Values',
    headerRow: 1,
    formulas: {
      G: `=ARRAYFORMULA(IF(E2:E="","",IFERROR(IF(VLOOKUP(E2:E,item_option_names,3,FALSE)="Flat Pricing","Flat Pricing",VLOOKUP(E2:E,item_option_names,4,FALSE)),"")))`,
      J: `=ARRAYFORMULA(LET(
  cat,D2:D, cost,H2:H, markup,I2:I,
  rate,Variables!$C$4,
  flat,(markup=1),
  gate,(cat<>"")*
       ((ISNUMBER(SEARCH("GLASS",cat))+ISNUMBER(SEARCH("IGU",cat))+ISNUMBER(SEARCH("MIRROR",cat)))>0)*
       ((ISNUMBER(SEARCH("HARDWARE",cat))+ISNUMBER(SEARCH("OTHER",cat)))=0)*
       (1-flat),
  IF(cost="","",cost*rate*gate)
))`,
      K: `=ARRAYFORMULA(LET(
  cat,D2:D, cost,H2:H, markup,I2:I,
  rate,Variables!$C$4, mode,Variables!$C$5,
  flat,(markup=1),
  gate,(cat<>"")*
       ((ISNUMBER(SEARCH("GLASS",cat))+ISNUMBER(SEARCH("IGU",cat))+ISNUMBER(SEARCH("MIRROR",cat)))>0)*
       ((ISNUMBER(SEARCH("HARDWARE",cat))+ISNUMBER(SEARCH("OTHER",cat)))=0)*
       (1-flat),
  surcharge,cost*rate*gate,
  IF(cost="","",IF(flat,0,cost+IF(mode="Markup",surcharge,0)))
))`,
      L: `=ARRAYFORMULA(LET(
  cat,D2:D, cost,H2:H, markup,I2:I,
  rate,Variables!$C$4, mode,Variables!$C$5,
  flat,(markup=1),
  gate,(cat<>"")*
       ((ISNUMBER(SEARCH("GLASS",cat))+ISNUMBER(SEARCH("IGU",cat))+ISNUMBER(SEARCH("MIRROR",cat)))>0)*
       ((ISNUMBER(SEARCH("HARDWARE",cat))+ISNUMBER(SEARCH("OTHER",cat)))=0)*
       (1-flat),
  surcharge,cost*rate*gate,
  landed,cost+IF(mode="Markup",surcharge,0),
  IF((cost="")+(markup="")>0,"",IF(flat,cost,landed*markup+IF(mode="Markup",0,surcharge)))
))`,
      M: `=ARRAYFORMULA(LET(
  cost,H2:H, price,L2:L, markup,I2:I,
  flat,(markup=1),
  IF(flat,
    IF(cost="","",1),
    IF((cost="")+(price="")+(IFERROR(cost*1,0)=0)>0,"",price/cost))
))`,
      N: `=ARRAYFORMULA(IF((A2:A=TRUE)*(E2:E<>""),E2:E,""))`,
      O: `=ARRAYFORMULA(IF((A2:A=TRUE)*(F2:F<>""),F2:F,""))`,
      P: `=ARRAYFORMULA(IF((A2:A=TRUE)*(E2:E<>""),IF(K2:K="",0,K2:K),0))`,
      Q: `=ARRAYFORMULA(IF((A2:A=TRUE)*(E2:E<>""),IF(L2:L="",0,L2:L),""))`
    }
  },

  // ===========================================================================
  // ITEM GROUPINGS â€” 31 ARRAYFORMULAs
  // ===========================================================================
  {
    name: 'Item Groupings',
    displayLabel: 'Item Groupings',
    headerRow: 1,
    formulas: {
      D: `=ARRAYFORMULA(IF((C2:C<>"")*(C2:C<>0), "From Item Repository", ""))`,
      E: `=ARRAYFORMULA(IF((C2:C<>"")*(C2:C<>0), 0, ""))`,
      G: `=ARRAYFORMULA(IF($F2:$F="", "", IFERROR(VLOOKUP($F2:$F, Items, 13, FALSE), "")))`,
      H: `=ARRAYFORMULA(IF($F2:$F="", "", IFERROR(VLOOKUP($F2:$F, items_selected, 2, FALSE), "")))`,
      I: `=ARRAYFORMULA(IF($F2:$F="", "", IFERROR(VLOOKUP($F2:$F, Items, 4, FALSE), "")))`,
      J: `=ARRAYFORMULA(IF($F2:$F="", "", IFERROR(VLOOKUP($F2:$F, Items, 8, FALSE), "")))`,
      K: `=ARRAYFORMULA(IF($F2:$F="", "", IFERROR(VLOOKUP($F2:$F, Items, 12, FALSE), "")))`,
      L: `=ARRAYFORMULA(IF($F2:$F="", "", IFERROR(VLOOKUP($F2:$F, Items, 11, FALSE), "")))`,
      M: `=ARRAYFORMULA(IF($F2:$F="", "", IFERROR(VLOOKUP($F2:$F, Items, 2, FALSE), "")))`,
      X:  `=ARRAYFORMULA(IF($A2:$A=TRUE, B2:B, IFERROR(1/0)))`,
      Y:  `=ARRAYFORMULA(IF($A2:$A=TRUE, C2:C, IFERROR(1/0)))`,
      Z:  `=ARRAYFORMULA(IF($A2:$A=TRUE, D2:D, IFERROR(1/0)))`,
      AA: `=ARRAYFORMULA(IF($A2:$A=TRUE, E2:E, IFERROR(1/0)))`,
      AB: `=ARRAYFORMULA(IF($A2:$A=TRUE, F2:F, IFERROR(1/0)))`,
      AC: `=ARRAYFORMULA(IF($A2:$A=TRUE, G2:G, IFERROR(1/0)))`,
      AD: `=ARRAYFORMULA(IF($A2:$A=TRUE, H2:H, IFERROR(1/0)))`,
      AE: `=ARRAYFORMULA(IF($A2:$A=TRUE, I2:I, IFERROR(1/0)))`,
      AF: `=ARRAYFORMULA(IF($A2:$A=TRUE, J2:J, IFERROR(1/0)))`,
      AG: `=ARRAYFORMULA(IF($A2:$A=TRUE, K2:K, IFERROR(1/0)))`,
      AH: `=ARRAYFORMULA(IF($A2:$A=TRUE, L2:L, IFERROR(1/0)))`,
      AI: `=ARRAYFORMULA(IF($A2:$A=TRUE, M2:M, IFERROR(1/0)))`,
      AJ: `=ARRAYFORMULA(IF($A2:$A=TRUE, N2:N, IFERROR(1/0)))`,
      AK: `=ARRAYFORMULA(IF($A2:$A=TRUE, O2:O, IFERROR(1/0)))`,
      AL: `=ARRAYFORMULA(IF($A2:$A=TRUE, P2:P, IFERROR(1/0)))`,
      AM: `=ARRAYFORMULA(IF($A2:$A=TRUE, Q2:Q, IFERROR(1/0)))`,
      AN: `=ARRAYFORMULA(IF($A2:$A=TRUE, R2:R, IFERROR(1/0)))`,
      AO: `=ARRAYFORMULA(IF($A2:$A=TRUE, S2:S, IFERROR(1/0)))`,
      AP: `=ARRAYFORMULA(IF($A2:$A=TRUE, T2:T, IFERROR(1/0)))`,
      AQ: `=ARRAYFORMULA(IF($A2:$A=TRUE, U2:U, IFERROR(1/0)))`,
      AR: `=ARRAYFORMULA(IF($A2:$A=TRUE, V2:V, IFERROR(1/0)))`,
      AS: `=ARRAYFORMULA(IF($A2:$A=TRUE, W2:W, IFERROR(1/0)))`
    }
  }
];

// ===========================================================================
// VARIABLES â€” Tier Cliff Tables (per-cell formulas, NOT ARRAYFORMULA)
// ===========================================================================
//
// Two tier tables live on the Variables sheet:
//   Glass & Mirrors          â€” rows 12â€“21 (10 tiers)
//   Hardware, Parts, Other   â€” rows 26â€“35 (10 tiers)
//
// Three formula columns per row:
//   G â€” Note text (range label)
//   I â€” Sell @ Ceiling   = C Ã— E + energy surcharge
//   K â€” Cliff to Next Tier = I(row) âˆ’ [ (C(row)+0.01) Ã— E(row+1) + energy ]
//
// G first row:   "Anything <= [ceiling]"
// G last row:    "Anything >= [ceiling]"
// G middle rows: "Anything > [prev+0.01] - [ceiling]"
// K last row:    static "â€”" (no next tier); NOT regenerated by repair.
//
// Energy surcharge is computed identically in I and K:
//   IF(energy_rate=0,0, base*energy_rate*IF(energy_method="Pass Through",1,markup))
//
// Repair is a separate Menu.gs function (e.g., repairVariablesTierFormulas())
// that consumes VARIABLES_TIER_FORMULAS and writes each cell individually.
// The CALC_SHEETS ARRAYFORMULA repair path does NOT apply here.

const VARIABLES_TIER_TABLES = [
  { name: 'Glass & Mirrors',        firstRow: 12, lastRow: 21 },
  { name: 'Hardware, Parts, Other', firstRow: 26, lastRow: 35 }
];

function buildVariablesTierFormulas_() {
  const out = {};
  VARIABLES_TIER_TABLES.forEach(function (t) {
    for (let r = t.firstRow; r <= t.lastRow; r++) {
      // G â€” Note text
      if (r === t.firstRow) {
        out['G' + r] = '="Anything <= "&TEXT(C' + r + ',"$#,##0.00")';
      } else if (r === t.lastRow) {
        out['G' + r] = '="Anything >= "&TEXT(C' + r + ',"$#,##0.00")';
      } else {
        out['G' + r] =
          '="Anything > "&TEXT(C' + (r - 1) + '+0.01,"$#,##0.00")&" - "&TEXT(C' + r + ',"$#,##0.00")';
      }
      // I â€” Sell @ Ceiling
      out['I' + r] =
        '=C' + r + '*E' + r +
        ' + IF(energy_rate=0,0,C' + r + '*energy_rate*IF(energy_method="Pass Through",1,E' + r + '))';
      // K â€” Cliff to Next Tier (skip last row; that cell stays as static "â€”")
      if (r < t.lastRow) {
        out['K' + r] =
          '=I' + r + ' - ((C' + r + '+0.01)*E' + (r + 1) +
          ' + IF(energy_rate=0,0,(C' + r + '+0.01)*energy_rate*IF(energy_method="Pass Through",1,E' + (r + 1) + ')))';
      }
    }
  });
  return out;
}

const VARIABLES_TIER_FORMULAS = buildVariablesTierFormulas_();

function colLetterToIndex_(letter) {
  let result = 0;
  const upper = String(letter).toUpperCase();
  for (let i = 0; i < upper.length; i++) {
    result = result * 26 + (upper.charCodeAt(i) - 64);
  }
  return result;
}

function calcSheetsTotalFormulas_() {
  let total = 0;
  for (let i = 0; i < CALC_SHEETS.length; i++) {
    total += Object.keys(CALC_SHEETS[i].formulas).length;
  }
  return total;
}

function variablesTierTotalFormulas_() {
  return Object.keys(VARIABLES_TIER_FORMULAS).length;
}
// clasp+git pipeline verified 2026-05-05
// Items section: +2 col shift for new source cols O/P; MIRRORâ†’MIRRORS in AK/AL; AM/AN removed; new AO/AP passthroughs; TRIM applied to all AO:AY passthroughs 2026-05-20
// Item Groupings G/H/J/K/L/M synced to live sheet 2026-05-20
// Variables tier formulas added (G/I/K, rows 12â€“21 + 26â€“35, 58 cells via generator) 2026-05-22
